global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "python_predictor"
    static_configs:
      - targets: ["10.156.115.33:9101"]
